//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolShop
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OrderProducts
    {
        public string productName
        {
            get
            {
                return App.Context.Products.Where(p => p.ID == ProductID).First().Title;
            }
        }
        public string correctImage
        {
            get
            {
                return App.Context.Products.Where(p => p.ID == ProductID).First().correctImage;
            }
        }
        public double price
        {
            get
            {
                return (double)App.Context.Products.Where(p => p.ID == ProductID).First().Price;
            }
        }
        public int amountInStock
        {
            get
            {
                return App.Context.Products.Where(p => p.ID == ProductID).First().AmountInStock;
            }
        }
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
