//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prdoucts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prdoucts()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ProductType { get; set; }
        public decimal Price { get; set; }
        public int AmountInStock { get; set; }
        public int ManufacturerID { get; set; }
        public int SupplierID { get; set; }
        public string Image { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
